version: '3'
services:
  exchange:
    build: .
    container_name: "exchange1"
    hostname: "exchange"
    command: ".\build.cmd BundleClient"
    # depends_on:
    #   - consul
  # consul:
  #   image: "consul:latest"
  #   container_name: "consul"
  #   hostname: "consul"
  #   ports:
  #     - "8084:8084"
  #   command: "agent -server -bootstrap -ui -disable-host-node-id -client 0.0.0.0"