// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Avalanchain")>]
[<assembly: AssemblyProductAttribute("Avalanchain")>]
[<assembly: AssemblyDescriptionAttribute("Avalanchain in F# for .NET")>]
[<assembly: AssemblyVersionAttribute("0.6.1")>]
[<assembly: AssemblyFileVersionAttribute("0.6.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Avalanchain"
    let [<Literal>] AssemblyProduct = "Avalanchain"
    let [<Literal>] AssemblyDescription = "Avalanchain in F# for .NET"
    let [<Literal>] AssemblyVersion = "0.6.1"
    let [<Literal>] AssemblyFileVersion = "0.6.1"
